plugins { id 'com.android.application' }

android {
    namespace 'it.cicciosfood.sunmi'
    compileSdk 33
    defaultConfig {
        applicationId 'it.cicciosfood.sunmi'
        minSdk 25
        targetSdk 28
        versionCode 2
        versionName '1.0.2'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'com.sunmi:printerlibrary:1.0.18'
}
